version: "3"

services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: weibersouza/nginx-app
    tty: true
    container_name: nginx-com-node
    networks:
      - my-network
    ports:
      - "8080:80"
    depends_on:
      - app
   
  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: mysql-db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
      - ./node/mysql:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - my-network
   

  app:
    build:
      context: ./node
      dockerfile: Dockerfile
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh
    command: node index.js
    container_name: app
    volumes:
      - ./node:/usr/src/app
      - /usr/src/app/node_modules
    tty: true
    networks:
      - my-network
    ports:
      - "3000:3000"
    depends_on:
      - db

networks:
  my-network:
    driver: bridge
